services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
#    command: bash -c "python manage.py collectstatic --noinput && gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --reload"
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    volumes:
      - ./mysite/:/app/
      - ./static:/app/static

  nginx: # Nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf:ro  # Монтируем конфиг Nginx
      - ./mysite/shopapp/static/shopapp/:/app/shopapp/static/shopapp/
      - ./static:/app/static
    depends_on:
      - app

volumes:
  static: